import { jsPDF } from "jspdf";
import type { CartItem } from "./cart-store";

export type Buyer = {
  name: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
};

export type Invoice = {
  id: string;
  date: string;
  items: CartItem[];
  buyer: Buyer;
  subtotal: number;
  shipping: number;
  total: number;
};

export function newInvoiceId() {
  const d = new Date();
  const stamp =
    d.getFullYear().toString().slice(-2) +
    String(d.getMonth() + 1).padStart(2, "0") +
    String(d.getDate()).padStart(2, "0");
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `SDF-${stamp}-${rand}`;
}

export function buildInvoice(items: CartItem[], buyer: Buyer): Invoice {
  const subtotal = items.reduce((n, i) => n + i.qty * i.product.price, 0);
  const shipping = subtotal > 500 ? 0 : 49;
  return {
    id: newInvoiceId(),
    date: new Date().toLocaleString("en-IN"),
    items,
    buyer,
    subtotal,
    shipping,
    total: subtotal + shipping,
  };
}

export function downloadInvoicePdf(inv: Invoice) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 56;

  // Header bar
  doc.setFillColor(10, 15, 10);
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(163, 230, 53);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("AGRIVIO", 40, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(220, 220, 210);
  doc.text("Growing Futures, One Seed at a Time", 40, 68);

  doc.setTextColor(220, 220, 210);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("TAX INVOICE", W - 40, 50, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Invoice: ${inv.id}`, W - 40, 65, { align: "right" });
  doc.text(`Date: ${inv.date}`, W - 40, 78, { align: "right" });

  y = 130;
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("BILL TO", 40, y);
  doc.text("SHIP FROM", W / 2 + 20, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  y += 16;
  doc.text(inv.buyer.name || "—", 40, y);
  doc.text("Agrivio (Student Initiative)", W / 2 + 20, y);
  y += 14;
  doc.text(inv.buyer.address || "", 40, y);
  doc.text("New Delhi, India", W / 2 + 20, y);
  y += 14;
  doc.text(
    `${inv.buyer.city || ""}${inv.buyer.city ? ", " : ""}${inv.buyer.state || ""} ${inv.buyer.pincode || ""}`,
    40,
    y,
  );
  doc.text("hello@agrivio.in", W / 2 + 20, y);
  y += 14;
  doc.text(`${inv.buyer.phone || ""}  ${inv.buyer.email || ""}`, 40, y);

  // Table header
  y += 30;
  doc.setFillColor(245, 247, 240);
  doc.rect(40, y - 14, W - 80, 22, "F");
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.text("Item", 50, y);
  doc.text("Unit", 320, y);
  doc.text("Qty", 400, y, { align: "right" });
  doc.text("Price", 470, y, { align: "right" });
  doc.text("Amount", W - 50, y, { align: "right" });

  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);

  inv.items.forEach((i) => {
    doc.text(i.product.name, 50, y);
    doc.text(i.product.unit, 320, y);
    doc.text(String(i.qty), 400, y, { align: "right" });
    doc.text(`₹${i.product.price}`, 470, y, { align: "right" });
    doc.text(`₹${i.product.price * i.qty}`, W - 50, y, { align: "right" });
    y += 18;
    doc.setDrawColor(230);
    doc.line(40, y - 8, W - 40, y - 8);
  });

  // Totals
  y += 18;
  const labelX = W - 180;
  const valX = W - 50;
  doc.text("Subtotal", labelX, y); doc.text(`₹${inv.subtotal}`, valX, y, { align: "right" });
  y += 16;
  doc.text("Shipping", labelX, y);
  doc.text(inv.shipping === 0 ? "FREE" : `₹${inv.shipping}`, valX, y, { align: "right" });
  y += 22;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Total", labelX, y);
  doc.text(`₹${inv.total}`, valX, y, { align: "right" });

  // Footer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text(
    "Thank you for supporting student-led sustainable farming. Payment on delivery.",
    40,
    780,
  );
  doc.text("This invoice was generated by agrivio.app", 40, 794);

  doc.save(`${inv.id}.pdf`);
}
