export type Product = {
  id: string;
  name: string;
  price: number;
  unit: string;
  category: "seed" | "sapling" | "manure" | "wellness";
  tagline: string;
  weather?: string;
  temp?: string;
  soil?: string;
  water?: string;
  season?: string;
  regions?: string[];
  benefits: string;
  emoji: string;
};

export const PRODUCTS: Product[] = [
  {
    id: "neem-sapling",
    name: "Neem Sapling",
    price: 49,
    unit: "each",
    category: "sapling",
    tagline: "Natural pesticide & shade tree",
    weather: "Hot & Dry",
    temp: "20–35°C",
    soil: "Well-drained",
    water: "Low",
    season: "Monsoon",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    benefits: "Natural pesticide, shade tree, medicinal leaves.",
    emoji: "🌱",
  },
  {
    id: "jamun-sapling",
    name: "Jamun Sapling",
    price: 79,
    unit: "each",
    category: "sapling",
    tagline: "Fruit-bearing canopy tree",
    weather: "Humid & Moderate",
    temp: "25–35°C",
    soil: "Loamy",
    water: "Medium",
    season: "Monsoon",
    regions: ["Uttar Pradesh", "Bihar", "Maharashtra"],
    benefits: "Fruit-bearing, supports pollinators, dense canopy.",
    emoji: "🫐",
  },
  {
    id: "moringa",
    name: "Moringa (Drumstick)",
    price: 39,
    unit: "each",
    category: "sapling",
    tagline: "Nutrient-rich fast grower",
    weather: "Warm Tropical",
    temp: "25–35°C",
    soil: "Sandy Loam",
    water: "Low",
    season: "Spring & Monsoon",
    regions: ["Tamil Nadu", "Karnataka", "Andhra Pradesh"],
    benefits: "Highly nutritious leaves & pods, fast-growing.",
    emoji: "🌿",
  },
  {
    id: "bamboo",
    name: "Bamboo",
    price: 99,
    unit: "each",
    category: "sapling",
    tagline: "Sustainable timber, soil binder",
    weather: "High Rainfall",
    temp: "20–30°C",
    soil: "Moist Loamy",
    water: "High",
    season: "Monsoon",
    regions: ["Assam", "Meghalaya", "Kerala"],
    benefits: "Soil binder, sustainable timber, fast carbon capture.",
    emoji: "🎋",
  },
  {
    id: "tomato-seed",
    name: "Heirloom Tomato Seeds",
    price: 29,
    unit: "20g pack",
    category: "seed",
    tagline: "Reliable kitchen-garden classic",
    weather: "Humid & Moderate",
    temp: "18–30°C",
    soil: "Loamy",
    water: "Medium",
    season: "Spring & Monsoon",
    regions: ["Maharashtra", "Karnataka", "Uttar Pradesh"],
    benefits: "High germination, firm fruit, disease-tolerant.",
    emoji: "🍅",
  },
  {
    id: "chili-seed",
    name: "Country Chili Seeds",
    price: 35,
    unit: "15g pack",
    category: "seed",
    tagline: "Pungent, sun-loving variety",
    weather: "Hot & Dry",
    temp: "22–35°C",
    soil: "Sandy Loam",
    water: "Low",
    season: "Spring & Monsoon",
    regions: ["Andhra Pradesh", "Tamil Nadu", "Gujarat"],
    benefits: "Strong heat, long shelf life, drought-friendly.",
    emoji: "🌶️",
  },
  // ── Cereals & grains ──────────────────────────────────────────
  { id: "basmati-rice", name: "Basmati Rice Seeds", price: 89, unit: "500g pack", category: "seed",
    tagline: "Aromatic long-grain paddy", weather: "Humid & Moderate", temp: "22–32°C",
    soil: "Clay Loam", water: "High", season: "Kharif",
    regions: ["Punjab", "Haryana", "Uttar Pradesh"],
    benefits: "Premium aroma, export-grade, high market value.", emoji: "🌾" },
  { id: "wheat-hd2967", name: "Wheat (HD-2967) Seeds", price: 65, unit: "1kg pack", category: "seed",
    tagline: "High-yield rust-resistant wheat", weather: "Cool & Dry", temp: "10–25°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Haryana", "Madhya Pradesh", "Uttar Pradesh"],
    benefits: "Rust-tolerant, strong tillering, dependable yield.", emoji: "🌾" },
  { id: "maize-hybrid", name: "Hybrid Maize Seeds", price: 75, unit: "500g pack", category: "seed",
    tagline: "Fast-growing fodder & food", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Sandy Loam", water: "Medium", season: "Kharif",
    regions: ["Bihar", "Karnataka", "Andhra Pradesh"],
    benefits: "Cob-rich, dual food and fodder use.", emoji: "🌽" },
  { id: "pearl-millet", name: "Pearl Millet (Bajra) Seeds", price: 45, unit: "500g pack", category: "seed",
    tagline: "Drought-hardy super grain", weather: "Hot & Dry", temp: "25–35°C",
    soil: "Sandy", water: "Low", season: "Kharif",
    regions: ["Rajasthan", "Gujarat", "Haryana"],
    benefits: "Thrives on minimal water, nutrient-dense.", emoji: "🌾" },
  { id: "finger-millet", name: "Ragi (Finger Millet) Seeds", price: 55, unit: "500g pack", category: "seed",
    tagline: "Calcium-rich ancient grain", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Well-drained", water: "Low", season: "Kharif",
    regions: ["Karnataka", "Tamil Nadu", "Andhra Pradesh"],
    benefits: "Highly nutritious, gluten-free superfood.", emoji: "🌾" },
  { id: "sorghum-jowar", name: "Sorghum (Jowar) Seeds", price: 50, unit: "500g pack", category: "seed",
    tagline: "Versatile grain & fodder", weather: "Hot & Dry", temp: "25–32°C",
    soil: "Well-drained", water: "Low", season: "Kharif",
    regions: ["Maharashtra", "Karnataka", "Andhra Pradesh"],
    benefits: "Drought-tolerant, dual-purpose crop.", emoji: "🌾" },

  // ── Pulses & legumes ──────────────────────────────────────────
  { id: "moong-dal", name: "Green Gram (Moong) Seeds", price: 60, unit: "500g pack", category: "seed",
    tagline: "Short-duration nitrogen fixer", weather: "Warm Tropical", temp: "25–35°C",
    soil: "Loamy", water: "Low", season: "Kharif",
    regions: ["Rajasthan", "Maharashtra", "Andhra Pradesh"],
    benefits: "Improves soil nitrogen, 60-day harvest.", emoji: "🫘" },
  { id: "toor-dal", name: "Pigeon Pea (Toor) Seeds", price: 55, unit: "500g pack", category: "seed",
    tagline: "Protein-packed pulse", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Well-drained", water: "Low", season: "Kharif",
    regions: ["Maharashtra", "Karnataka", "Madhya Pradesh"],
    benefits: "High protein, deep-rooted soil enricher.", emoji: "🫘" },
  { id: "chickpea", name: "Chickpea (Chana) Seeds", price: 65, unit: "500g pack", category: "seed",
    tagline: "Winter pulse staple", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Low", season: "Rabi",
    regions: ["Madhya Pradesh", "Rajasthan", "Maharashtra"],
    benefits: "Fixes nitrogen, robust winter crop.", emoji: "🫘" },
  { id: "urad-dal", name: "Black Gram (Urad) Seeds", price: 60, unit: "500g pack", category: "seed",
    tagline: "Rich protein legume", weather: "Humid & Moderate", temp: "25–35°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Andhra Pradesh", "Tamil Nadu", "Maharashtra"],
    benefits: "Improves soil health, high protein yield.", emoji: "🫘" },
  { id: "lentil-masoor", name: "Lentil (Masoor) Seeds", price: 55, unit: "500g pack", category: "seed",
    tagline: "Hardy winter lentil", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Low", season: "Rabi",
    regions: ["Uttar Pradesh", "Bihar", "Madhya Pradesh"],
    benefits: "Quick-cooking, iron-rich pulse.", emoji: "🫘" },
  { id: "rajma-kidney", name: "Kidney Bean (Rajma) Seeds", price: 70, unit: "500g pack", category: "seed",
    tagline: "Hearty hill legume", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Jammu & Kashmir", "Himachal Pradesh", "Uttarakhand"],
    benefits: "Protein-rich, thrives in cool climates.", emoji: "🫘" },

  // ── Vegetables ────────────────────────────────────────────────
  { id: "brinjal-seed", name: "Brinjal (Baingan) Seeds", price: 30, unit: "10g pack", category: "seed",
    tagline: "Glossy purple staple", weather: "Warm Tropical", temp: "22–30°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["West Bengal", "Odisha", "Karnataka"],
    benefits: "Prolific fruiter, disease-resistant.", emoji: "🍆" },
  { id: "okra-seed", name: "Lady Finger (Bhindi) Seeds", price: 25, unit: "20g pack", category: "seed",
    tagline: "Tender summer producer", weather: "Warm Tropical", temp: "24–35°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Uttar Pradesh", "Gujarat", "Andhra Pradesh"],
    benefits: "Continuous harvest for 3 months.", emoji: "🌱" },
  { id: "onion-seed", name: "Red Onion Seeds", price: 40, unit: "50g pack", category: "seed",
    tagline: "Storage-friendly bulbs", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Sandy Loam", water: "Medium", season: "Rabi",
    regions: ["Maharashtra", "Karnataka", "Gujarat"],
    benefits: "Long shelf life, strong pungency.", emoji: "🧅" },
  { id: "carrot-seed", name: "Carrot Seeds", price: 35, unit: "10g pack", category: "seed",
    tagline: "Sweet crunchy roots", weather: "Cool & Dry", temp: "10–20°C",
    soil: "Sandy Loam", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Haryana", "Himachal Pradesh"],
    benefits: "Vitamin-A rich, fast maturing.", emoji: "🥕" },
  { id: "radish-seed", name: "Radish (Mooli) Seeds", price: 20, unit: "20g pack", category: "seed",
    tagline: "Cool-season quick crop", weather: "Cool & Dry", temp: "10–22°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Uttar Pradesh", "West Bengal"],
    benefits: "40-day harvest, easy grower.", emoji: "🌱" },
  { id: "spinach-seed", name: "Spinach (Palak) Seeds", price: 25, unit: "50g pack", category: "seed",
    tagline: "Iron-rich leafy green", weather: "Cool & Dry", temp: "10–25°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Uttar Pradesh", "West Bengal"],
    benefits: "Multiple cuttings, nutrient dense.", emoji: "🥬" },
  { id: "coriander-seed", name: "Coriander (Dhania) Seeds", price: 30, unit: "50g pack", category: "seed",
    tagline: "Fragrant kitchen herb", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    benefits: "Dual use — leaves and seeds.", emoji: "🌿" },
  { id: "fenugreek-seed", name: "Fenugreek (Methi) Seeds", price: 25, unit: "50g pack", category: "seed",
    tagline: "Bitter-sweet green & spice", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Low", season: "Rabi",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    benefits: "Soil enricher, medicinal leaves.", emoji: "🌿" },
  { id: "cabbage-seed", name: "Cabbage Seeds", price: 45, unit: "10g pack", category: "seed",
    tagline: "Compact winter head", weather: "Cool & Dry", temp: "15–20°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["West Bengal", "Bihar", "Himachal Pradesh"],
    benefits: "Firm heads, cool-weather champion.", emoji: "🥬" },
  { id: "cauliflower-seed", name: "Cauliflower Seeds", price: 50, unit: "10g pack", category: "seed",
    tagline: "Snow-white curd variety", weather: "Cool & Dry", temp: "15–22°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Haryana", "West Bengal"],
    benefits: "Uniform curds, market favourite.", emoji: "🥦" },
  { id: "cucumber-seed", name: "Cucumber Seeds", price: 30, unit: "10g pack", category: "seed",
    tagline: "Refreshing summer vine", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Sandy Loam", water: "Medium", season: "Spring & Monsoon",
    regions: ["Karnataka", "Maharashtra", "Uttar Pradesh"],
    benefits: "Prolific, thirst-quenching harvest.", emoji: "🥒" },
  { id: "bitter-gourd-seed", name: "Bitter Gourd (Karela) Seeds", price: 40, unit: "10g pack", category: "seed",
    tagline: "Medicinal climbing vine", weather: "Warm Tropical", temp: "25–35°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["West Bengal", "Bihar", "Karnataka"],
    benefits: "Blood-sugar friendly, easy trellising.", emoji: "🥒" },
  { id: "bottle-gourd-seed", name: "Bottle Gourd (Lauki) Seeds", price: 35, unit: "10g pack", category: "seed",
    tagline: "Fast summer climber", weather: "Warm Tropical", temp: "24–32°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Uttar Pradesh", "Bihar", "Maharashtra"],
    benefits: "High yield, cooling vegetable.", emoji: "🥒" },
  { id: "pumpkin-seed", name: "Pumpkin (Kaddu) Seeds", price: 30, unit: "10g pack", category: "seed",
    tagline: "Sprawling autumn crop", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Uttar Pradesh", "Bihar", "Odisha"],
    benefits: "Long storage, sweet flesh.", emoji: "🎃" },
  { id: "potato-seed", name: "Seed Potato (Kufri Jyoti)", price: 120, unit: "2kg", category: "seed",
    tagline: "Certified tuber seed", weather: "Cool & Dry", temp: "15–20°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Punjab", "Uttar Pradesh", "West Bengal"],
    benefits: "Disease-free tubers, high yield.", emoji: "🥔" },
  { id: "peas-seed", name: "Garden Peas Seeds", price: 45, unit: "250g pack", category: "seed",
    tagline: "Sweet winter pods", weather: "Cool & Dry", temp: "10–20°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Uttar Pradesh", "Punjab", "Himachal Pradesh"],
    benefits: "Nitrogen fixer, tender sweet peas.", emoji: "🫛" },

  // ── Oilseeds ──────────────────────────────────────────────────
  { id: "mustard-seed", name: "Mustard (Sarson) Seeds", price: 55, unit: "500g pack", category: "seed",
    tagline: "Golden winter oilseed", weather: "Cool & Dry", temp: "10–25°C",
    soil: "Loamy", water: "Low", season: "Rabi",
    regions: ["Rajasthan", "Uttar Pradesh", "Haryana"],
    benefits: "Oil-rich, hardy winter crop.", emoji: "🌼" },
  { id: "groundnut-seed", name: "Groundnut (Peanut) Seeds", price: 90, unit: "1kg pack", category: "seed",
    tagline: "Underground protein oilseed", weather: "Warm Tropical", temp: "25–30°C",
    soil: "Sandy Loam", water: "Low", season: "Kharif",
    regions: ["Gujarat", "Andhra Pradesh", "Tamil Nadu"],
    benefits: "Nitrogen fixer, oil-rich kernels.", emoji: "🥜" },
  { id: "sesame-seed", name: "Sesame (Til) Seeds", price: 70, unit: "250g pack", category: "seed",
    tagline: "Ancient drought crop", weather: "Hot & Dry", temp: "25–35°C",
    soil: "Sandy Loam", water: "Low", season: "Kharif",
    regions: ["Gujarat", "Rajasthan", "Madhya Pradesh"],
    benefits: "Drought hardy, high oil content.", emoji: "🌱" },
  { id: "sunflower-seed", name: "Sunflower Seeds", price: 60, unit: "250g pack", category: "seed",
    tagline: "Cheerful oil & pollinator crop", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Karnataka", "Andhra Pradesh", "Maharashtra"],
    benefits: "Bee-friendly, edible seeds & oil.", emoji: "🌻" },
  { id: "soybean-seed", name: "Soybean Seeds", price: 80, unit: "500g pack", category: "seed",
    tagline: "Protein powerhouse legume", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Madhya Pradesh", "Maharashtra", "Rajasthan"],
    benefits: "40% protein, soil-nitrogen fixer.", emoji: "🫘" },

  // ── Spices & herbs ────────────────────────────────────────────
  { id: "turmeric-seed", name: "Turmeric Rhizome Seeds", price: 110, unit: "500g", category: "seed",
    tagline: "Golden medicinal rhizome", weather: "Humid & Moderate", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Andhra Pradesh", "Tamil Nadu", "Maharashtra"],
    benefits: "Antioxidant, cash-crop favourite.", emoji: "🌿" },
  { id: "ginger-seed", name: "Ginger Rhizome Seeds", price: 130, unit: "500g", category: "seed",
    tagline: "Aromatic spice rhizome", weather: "Humid & Moderate", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Kharif",
    regions: ["Kerala", "Karnataka", "Meghalaya"],
    benefits: "High-value spice, shade-tolerant.", emoji: "🌱" },
  { id: "cumin-seed", name: "Cumin (Jeera) Seeds", price: 90, unit: "100g pack", category: "seed",
    tagline: "Fragrant desert spice", weather: "Cool & Dry", temp: "10–25°C",
    soil: "Sandy Loam", water: "Low", season: "Rabi",
    regions: ["Rajasthan", "Gujarat"],
    benefits: "Aromatic, high-value spice crop.", emoji: "🌿" },
  { id: "fennel-seed", name: "Fennel (Saunf) Seeds", price: 80, unit: "100g pack", category: "seed",
    tagline: "Sweet aromatic herb", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    benefits: "Digestive spice, quick market sale.", emoji: "🌿" },
  { id: "ajwain-seed", name: "Carom (Ajwain) Seeds", price: 75, unit: "100g pack", category: "seed",
    tagline: "Pungent medicinal herb", weather: "Cool & Dry", temp: "15–25°C",
    soil: "Loamy", water: "Low", season: "Rabi",
    regions: ["Rajasthan", "Madhya Pradesh", "Gujarat"],
    benefits: "Digestive aid, easy-grow herb.", emoji: "🌿" },
  { id: "black-pepper", name: "Black Pepper Vine Seeds", price: 160, unit: "50g pack", category: "seed",
    tagline: "King of spices climber", weather: "High Rainfall", temp: "20–30°C",
    soil: "Loamy", water: "High", season: "Monsoon",
    regions: ["Kerala", "Karnataka", "Tamil Nadu"],
    benefits: "Export-grade spice, shade climber.", emoji: "🌿" },
  { id: "cardamom-seed", name: "Cardamom Seedlings", price: 199, unit: "each", category: "seed",
    tagline: "Queen of spices", weather: "High Rainfall", temp: "18–28°C",
    soil: "Loamy", water: "High", season: "Monsoon",
    regions: ["Kerala", "Karnataka", "Sikkim"],
    benefits: "Premium spice, long-yielding plant.", emoji: "🌿" },
  { id: "tulsi-seed", name: "Tulsi (Holy Basil) Seeds", price: 25, unit: "5g pack", category: "seed",
    tagline: "Sacred medicinal herb", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Low", season: "Spring & Monsoon",
    regions: ["All India"],
    benefits: "Immunity herb, easy container grow.", emoji: "🌿" },
  { id: "ashwagandha-seed", name: "Ashwagandha Seeds", price: 60, unit: "20g pack", category: "seed",
    tagline: "Ayurvedic root herb", weather: "Hot & Dry", temp: "20–35°C",
    soil: "Sandy Loam", water: "Low", season: "Kharif",
    regions: ["Rajasthan", "Madhya Pradesh", "Gujarat"],
    benefits: "High-value medicinal root crop.", emoji: "🌿" },
  { id: "aloe-vera-pups", name: "Aloe Vera Pups", price: 49, unit: "each", category: "sapling",
    tagline: "Healing succulent", weather: "Hot & Dry", temp: "20–35°C",
    soil: "Sandy", water: "Low", season: "Spring & Monsoon",
    regions: ["Rajasthan", "Gujarat", "Tamil Nadu"],
    benefits: "Medicinal gel, drought-tolerant.", emoji: "🌵" },

  // ── Flowers ───────────────────────────────────────────────────
  { id: "marigold-seed", name: "Marigold (Genda) Seeds", price: 30, unit: "10g pack", category: "seed",
    tagline: "Festival flower & pest guard", weather: "Warm Tropical", temp: "18–30°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Karnataka", "West Bengal", "Maharashtra"],
    benefits: "Natural pest repellent, quick blooms.", emoji: "🌼" },
  { id: "rose-cuttings", name: "Desi Rose Cuttings", price: 89, unit: "each", category: "sapling",
    tagline: "Fragrant garden classic", weather: "Cool & Dry", temp: "15–28°C",
    soil: "Loamy", water: "Medium", season: "Rabi",
    regions: ["Uttar Pradesh", "Rajasthan", "Karnataka"],
    benefits: "Perennial beauty, pollinator draw.", emoji: "🌹" },
  { id: "sunflower-ornamental", name: "Ornamental Sunflower Seeds", price: 45, unit: "20g pack", category: "seed",
    tagline: "Bold golden blooms", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Karnataka", "Andhra Pradesh"],
    benefits: "Bee-friendly, dramatic garden accent.", emoji: "🌻" },
  { id: "hibiscus-cuttings", name: "Hibiscus Cuttings", price: 69, unit: "each", category: "sapling",
    tagline: "Year-round flowering shrub", weather: "Warm Tropical", temp: "20–32°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Kerala", "Tamil Nadu", "West Bengal"],
    benefits: "Medicinal, continuous flowering.", emoji: "🌺" },

  // ── Fruit saplings ────────────────────────────────────────────
  { id: "mango-sapling", name: "Alphonso Mango Sapling", price: 249, unit: "each", category: "sapling",
    tagline: "King of fruits — grafted", weather: "Warm Tropical", temp: "24–35°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Maharashtra", "Gujarat", "Karnataka"],
    benefits: "Grafted for early fruiting, premium.", emoji: "🥭" },
  { id: "papaya-sapling", name: "Papaya (Red Lady) Sapling", price: 79, unit: "each", category: "sapling",
    tagline: "Fast fruit-bearer", weather: "Warm Tropical", temp: "22–32°C",
    soil: "Loamy", water: "Medium", season: "Spring & Monsoon",
    regions: ["Andhra Pradesh", "Karnataka", "Gujarat"],
    benefits: "Fruits in 9 months, high yield.", emoji: "🌴" },
  { id: "banana-sapling", name: "Banana (G-9) Sapling", price: 59, unit: "each", category: "sapling",
    tagline: "Commercial dessert banana", weather: "Humid & Moderate", temp: "22–32°C",
    soil: "Loamy", water: "High", season: "Monsoon",
    regions: ["Tamil Nadu", "Maharashtra", "Gujarat"],
    benefits: "Tissue-cultured, uniform bunches.", emoji: "🍌" },
  { id: "guava-sapling", name: "Guava (Allahabad Safeda) Sapling", price: 129, unit: "each", category: "sapling",
    tagline: "Sweet high-vitamin fruit", weather: "Warm Tropical", temp: "20–30°C",
    soil: "Loamy", water: "Medium", season: "Monsoon",
    regions: ["Uttar Pradesh", "Bihar", "Maharashtra"],
    benefits: "Reliable fruiting, hardy tree.", emoji: "🍈" },
  { id: "pomegranate-sapling", name: "Pomegranate (Bhagwa) Sapling", price: 139, unit: "each", category: "sapling",
    tagline: "Drought-hardy red-jewel fruit", weather: "Hot & Dry", temp: "20–35°C",
    soil: "Well-drained", water: "Low", season: "Monsoon",
    regions: ["Maharashtra", "Karnataka", "Rajasthan"],
    benefits: "Export variety, low water need.", emoji: "🍎" },
  { id: "lemon-sapling", name: "Kagzi Lemon Sapling", price: 99, unit: "each", category: "sapling",
    tagline: "Thin-skinned juicy lemon", weather: "Warm Tropical", temp: "20–32°C",
    soil: "Loamy", water: "Medium", season: "Monsoon",
    regions: ["Andhra Pradesh", "Maharashtra", "Gujarat"],
    benefits: "Year-round fruiting, kitchen staple.", emoji: "🍋" },
  { id: "curry-leaf-sapling", name: "Curry Leaf Sapling", price: 59, unit: "each", category: "sapling",
    tagline: "Essential kitchen herb tree", weather: "Warm Tropical", temp: "20–32°C",
    soil: "Loamy", water: "Low", season: "Spring & Monsoon",
    regions: ["Tamil Nadu", "Karnataka", "Kerala"],
    benefits: "Everyday spice, hardy grower.", emoji: "🌿" },

  // ── Manure & compost ──────────────────────────────────────────
  { id: "organic-manure", name: "Organic Manure", price: 120, unit: "5kg", category: "manure",
    tagline: "Composted fruit peels & farm waste",
    benefits: "Restores soil fertility naturally.", emoji: "🪴" },
  { id: "neem-cake", name: "Neem Cake", price: 150, unit: "2kg", category: "manure",
    tagline: "Natural pest deterrent",
    benefits: "Soil enricher and pest deterrent.", emoji: "🌾" },
  { id: "vermicompost", name: "Vermicompost", price: 180, unit: "5kg", category: "manure",
    tagline: "Earthworm-processed compost",
    benefits: "Boosts microbial activity in soil.", emoji: "🐛" },
  { id: "jamun-powder", name: "Jamun Seed Powder", price: 220, unit: "250g", category: "wellness",
    tagline: "Heritage food product",
    benefits: "Traditional wellness from sun-dried jamun seeds.", emoji: "🫙" },
];

export const STATES = [
  "All","All India","Andhra Pradesh","Assam","Bihar","Gujarat","Haryana",
  "Himachal Pradesh","Jammu & Kashmir","Karnataka","Kerala","Madhya Pradesh",
  "Maharashtra","Meghalaya","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu",
  "Uttar Pradesh","Uttarakhand","West Bengal",
];
export const WEATHERS = ["All","Cool & Dry","High Rainfall","Hot & Dry","Humid & Moderate","Warm Tropical"];
export const SEASONS = ["All","Kharif","Monsoon","Rabi","Spring & Monsoon"];
export const SOILS = ["All","Clay Loam","Loamy","Moist Loamy","Sandy","Sandy Loam","Well-drained"];
export const WATERS = ["All","Low","Medium","High"];

